### PR TITLE
Updated AWS dependency to use SQS directly.

### PR DESCRIPTION
**Pull request by enragedginger**

### CODE REVIEW

**Comment by lbradstreet** [comment]
Thanks! I'll test this before I merge, as CI doesn't run on PRs since it needs our creds.

**Comment by enragedginger** [comment]
@lbradstreet Any updates on this?

**Comment by lbradstreet** [comment]
Sorry, I had forgotten about this. Looks good - merged.

**Comment by lbradstreet** [comment]
Snapshot dependency is available at `0.12.0.0-20171113.200644-4`. We should have an official release in the next few days.

**Pull request merged**
